/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "surface-bright": "#3a3939",
        primary: "#ffb4ab",
        "primary-container": "#b91c1c",
        "on-primary": "#690005",
        "on-primary-container": "#ffcdc7",
        secondary: "#ffb3ad",
        "secondary-container": "#a40217",
        tertiary: "#ffb95f",
        "tertiary-container": "#855300",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#e4beb9",
        outline: "#ab8985",
        "outline-variant": "#5b403d",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "status-paid": "#22c55e",
        "status-pending": "#eab308",
        "status-late": "#ef4444",
        "status-exempt": "#6b7280",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Montserrat", "sans-serif"],
      },
    },
  },
  plugins: [],
};
