// <auto-generated />
using System;
using Forja.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forja.Api.Data.Migrations
{
    [DbContext(typeof(ForjaDbContext))]
    [Migration("20260910002515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forja.Api.Domain.Academy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("academies", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.CategoryEnrollment", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("WeighedIn")
                        .HasColumnType("boolean");

                    b.HasKey("CategoryId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("category_enrollments", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Fighter1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Fighter2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Score")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VictoryType")
                        .HasColumnType("text");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Fighter1Id");

                    b.HasIndex("Fighter2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_month", "month >= 1 AND month <= 12");

                            t.HasCheckConstraint("ck_payments_year", "year >= 2020");
                        });
                });

            modelBuilder.Entity("Forja.Api.Domain.ProfessorTeam", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfessorId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("professor_teams", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Belt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Degrees")
                        .HasColumnType("integer");

                    b.Property<int>("DueDay")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("ck_students_degrees", "degrees >= 0 AND degrees <= 4");

                            t.HasCheckConstraint("ck_students_due_day", "due_day >= 1 AND due_day <= 31");
                        });
                });

            modelBuilder.Entity("Forja.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Rules")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademyId");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.TournamentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Belt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxWeight")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("tournament_categories", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.CategoryEnrollment", b =>
                {
                    b.HasOne("Forja.Api.Domain.TournamentCategory", "Category")
                        .WithMany("Enrollments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forja.Api.Domain.Student", "Student")
                        .WithMany("CategoryEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Forja.Api.Domain.Match", b =>
                {
                    b.HasOne("Forja.Api.Domain.TournamentCategory", "Category")
                        .WithMany("Matches")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forja.Api.Domain.Student", "Fighter1")
                        .WithMany()
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Forja.Api.Domain.Student", "Fighter2")
                        .WithMany()
                        .HasForeignKey("Fighter2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Forja.Api.Domain.Student", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Fighter1");

                    b.Navigation("Fighter2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Forja.Api.Domain.Payment", b =>
                {
                    b.HasOne("Forja.Api.Domain.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Forja.Api.Domain.ProfessorTeam", b =>
                {
                    b.HasOne("Forja.Api.Domain.Profile", "Professor")
                        .WithMany("ProfessorTeams")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forja.Api.Domain.Team", "Team")
                        .WithMany("ProfessorTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Forja.Api.Domain.Student", b =>
                {
                    b.HasOne("Forja.Api.Domain.Academy", "Academy")
                        .WithMany("Students")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forja.Api.Domain.Profile", "Profile")
                        .WithOne("Student")
                        .HasForeignKey("Forja.Api.Domain.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forja.Api.Domain.Team", "Team")
                        .WithMany("Students")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academy");

                    b.Navigation("Profile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Forja.Api.Domain.Team", b =>
                {
                    b.HasOne("Forja.Api.Domain.Academy", "Academy")
                        .WithMany("Teams")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academy");
                });

            modelBuilder.Entity("Forja.Api.Domain.Tournament", b =>
                {
                    b.HasOne("Forja.Api.Domain.Academy", "Academy")
                        .WithMany("Tournaments")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academy");
                });

            modelBuilder.Entity("Forja.Api.Domain.TournamentCategory", b =>
                {
                    b.HasOne("Forja.Api.Domain.Tournament", "Tournament")
                        .WithMany("Categories")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Forja.Api.Domain.Academy", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teams");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Forja.Api.Domain.Profile", b =>
                {
                    b.Navigation("ProfessorTeams");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Forja.Api.Domain.Student", b =>
                {
                    b.Navigation("CategoryEnrollments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Forja.Api.Domain.Team", b =>
                {
                    b.Navigation("ProfessorTeams");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Forja.Api.Domain.Tournament", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Forja.Api.Domain.TournamentCategory", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
