// <auto-generated />
using System;
using Forja.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forja.Api.Data.Migrations
{
    [DbContext(typeof(ForjaDbContext))]
    partial class ForjaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forja.Api.Domain.Academy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_academies");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_academies_slug");

                    b.ToTable("academies", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.CategoryEnrollment", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("WeighedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("weighed_in");

                    b.HasKey("CategoryId", "StudentId")
                        .HasName("pk_category_enrollments");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_category_enrollments_student_id");

                    b.ToTable("category_enrollments", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Fighter1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("fighter1_id");

                    b.Property<Guid?>("Fighter2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("fighter2_id");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("round_name");

                    b.Property<string>("Score")
                        .HasColumnType("text")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VictoryType")
                        .HasColumnType("text")
                        .HasColumnName("victory_type");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_matches_category_id");

                    b.HasIndex("Fighter1Id")
                        .HasDatabaseName("ix_matches_fighter1_id");

                    b.HasIndex("Fighter2Id")
                        .HasDatabaseName("ix_matches_fighter2_id");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("ix_matches_winner_id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Method")
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payments_status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_payments_student_id");

                    b.HasIndex("StudentId", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_student_id_month_year");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_month", "month >= 1 AND month <= 12");

                            t.HasCheckConstraint("ck_payments_year", "year >= 2020");
                        });
                });

            modelBuilder.Entity("Forja.Api.Domain.ProfessorTeam", b =>
                {
                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid")
                        .HasColumnName("professor_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("ProfessorId", "TeamId")
                        .HasName("pk_professor_teams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_professor_teams_team_id");

                    b.ToTable("professor_teams", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_email");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<string>("Belt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("belt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Degrees")
                        .HasColumnType("integer")
                        .HasColumnName("degrees");

                    b.Property<int>("DueDay")
                        .HasColumnType("integer")
                        .HasColumnName("due_day");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("AcademyId")
                        .HasDatabaseName("ix_students_academy_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_students_status");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_students_team_id");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("ck_students_degrees", "degrees >= 0 AND degrees <= 4");

                            t.HasCheckConstraint("ck_students_due_day", "due_day >= 1 AND due_day <= 31");
                        });
                });

            modelBuilder.Entity("Forja.Api.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Schedule")
                        .HasColumnType("text")
                        .HasColumnName("schedule");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("AcademyId")
                        .HasDatabaseName("ix_teams_academy_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AcademyId")
                        .HasColumnType("uuid")
                        .HasColumnName("academy_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Rules")
                        .HasColumnType("text")
                        .HasColumnName("rules");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tournaments");

                    b.HasIndex("AcademyId")
                        .HasDatabaseName("ix_tournaments_academy_id");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.TournamentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("age_group");

                    b.Property<string>("Belt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("belt");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<decimal?>("MaxWeight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("max_weight");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id")
                        .HasName("pk_tournament_categories");

                    b.HasIndex("TournamentId")
                        .HasDatabaseName("ix_tournament_categories_tournament_id");

                    b.ToTable("tournament_categories", (string)null);
                });

            modelBuilder.Entity("Forja.Api.Domain.CategoryEnrollment", b =>
                {
                    b.HasOne("Forja.Api.Domain.TournamentCategory", "Category")
                        .WithMany("Enrollments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_enrollments_tournament_categories_category_id");

                    b.HasOne("Forja.Api.Domain.Student", "Student")
                        .WithMany("CategoryEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_enrollments_students_student_id");

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Forja.Api.Domain.Match", b =>
                {
                    b.HasOne("Forja.Api.Domain.TournamentCategory", "Category")
                        .WithMany("Matches")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_tournament_categories_category_id");

                    b.HasOne("Forja.Api.Domain.Student", "Fighter1")
                        .WithMany()
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_students_fighter1_id");

                    b.HasOne("Forja.Api.Domain.Student", "Fighter2")
                        .WithMany()
                        .HasForeignKey("Fighter2Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_students_fighter2_id");

                    b.HasOne("Forja.Api.Domain.Student", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_students_winner_id");

                    b.Navigation("Category");

                    b.Navigation("Fighter1");

                    b.Navigation("Fighter2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Forja.Api.Domain.Payment", b =>
                {
                    b.HasOne("Forja.Api.Domain.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_students_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Forja.Api.Domain.ProfessorTeam", b =>
                {
                    b.HasOne("Forja.Api.Domain.Profile", "Professor")
                        .WithMany("ProfessorTeams")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professor_teams_profiles_professor_id");

                    b.HasOne("Forja.Api.Domain.Team", "Team")
                        .WithMany("ProfessorTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professor_teams_teams_team_id");

                    b.Navigation("Professor");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Forja.Api.Domain.Student", b =>
                {
                    b.HasOne("Forja.Api.Domain.Academy", "Academy")
                        .WithMany("Students")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_academies_academy_id");

                    b.HasOne("Forja.Api.Domain.Profile", "Profile")
                        .WithOne("Student")
                        .HasForeignKey("Forja.Api.Domain.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_profiles_id");

                    b.HasOne("Forja.Api.Domain.Team", "Team")
                        .WithMany("Students")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_teams_team_id");

                    b.Navigation("Academy");

                    b.Navigation("Profile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Forja.Api.Domain.Team", b =>
                {
                    b.HasOne("Forja.Api.Domain.Academy", "Academy")
                        .WithMany("Teams")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_academies_academy_id");

                    b.Navigation("Academy");
                });

            modelBuilder.Entity("Forja.Api.Domain.Tournament", b =>
                {
                    b.HasOne("Forja.Api.Domain.Academy", "Academy")
                        .WithMany("Tournaments")
                        .HasForeignKey("AcademyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournaments_academies_academy_id");

                    b.Navigation("Academy");
                });

            modelBuilder.Entity("Forja.Api.Domain.TournamentCategory", b =>
                {
                    b.HasOne("Forja.Api.Domain.Tournament", "Tournament")
                        .WithMany("Categories")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tournament_categories_tournaments_tournament_id");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Forja.Api.Domain.Academy", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teams");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Forja.Api.Domain.Profile", b =>
                {
                    b.Navigation("ProfessorTeams");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Forja.Api.Domain.Student", b =>
                {
                    b.Navigation("CategoryEnrollments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Forja.Api.Domain.Team", b =>
                {
                    b.Navigation("ProfessorTeams");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Forja.Api.Domain.Tournament", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Forja.Api.Domain.TournamentCategory", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
